# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corphylo_LL <- function(par, XX, UU, MM, tau, Vphy, REML = TRUE, constrain_d = FALSE) {
    .Call('_corphyloCpp_corphylo_LL', PACKAGE = 'corphyloCpp', par, XX, UU, MM, tau, Vphy, REML, constrain_d)
}

