

<!---
This document talks about and produces a phylogenetic tree for the supplemental info.
-->

```{r packages_data, echo = FALSE}
suppressPackageStartupMessages({
    library(ape)
    library(dplyr)
    library(ggplot2)
    library(ggtree)
    library(ggimage)
})
invisible(sapply(list.files('R', '*.R', full.names = TRUE), source))
morph_df <- get_df('spp')
tr <- get_tr('spp') # <-- full tree
absorp_df <- get_df('absorp')
clear_df <- get_df('clear')

# Data frame of which datasets each species is in:
data_df <- morph_df %>%
    distinct(species) %>% 
    mutate(`morph.` = TRUE, 
           `absorp.` = species %in% absorp_df$species,
           `clear.` = species %in% clear_df$species)
rownames(data_df) <- data_df$species
data_df <- data_df[, -1]
# Useful if you keep getting `polygon edge not found` error
# From here: http://disq.us/t/24rt791
# options("device" = "quartz"); graphics.off()
```




```{r phylo_plot, echo = FALSE, fig.cap = "Phylogeny of species used in these analyses. Boxes on the right indicate whether the species was used in morphometric (\"morph.\"), absorption (\"absorp.\"), or clearance (\"clear.\") analyses. Gray boxes indicate a species was absent."}
x_end <- 32
gg_tr <- ggtree(tr)
gg_tr$data$x <- gg_tr$data$x - max(gg_tr$data$x)
gg_tr <- gg_tr + #%<+% {sp_df %>% select(species, everything())} +
    theme_tree2(axis.title.x = element_blank(),
                axis.text.x = element_blank(),
                axis.ticks.x = element_blank(),
                plot.margin = margin(0,0,0,0)) +
    geom_tiplab(aes(x = x + 2), size = 3, fontface = 'bold.italic')# +
    # geom_tippoint(aes(x = x))
suppressMessages(
    gg_tr <- gheatmap(gg_tr, data_df, offset = 38, width = 0.2, font.size = 2.5, 
                      colnames_position ='bottom', colnames_angle = -30, 
                      colnames_offset_y = -0.25, colnames_offset_x = 2) +
        scale_fill_manual(breaks = c(TRUE, FALSE),  values = c("gray50", "dodgerblue"),
                          guide = FALSE) + 
        geom_treescale(x = -90, y = 15, offset = 0.5, width = 10)
    # scale_x_continuous('Time (mya)', limits = c(-100, x_end + 25),
    #                breaks = seq(-100, 0, 25), labels = seq(100, 0, -25)) +
    # scale_y_continuous(limits = c(-5, 30))
)
gg_tr + 
    # Bat image
    geom_phylopic(image = "18bfd2fc-f184-4c3a-b511-796aafcc70f6",
                           color = "firebrick", 
                           data = NULL, inherit.aes = FALSE,
                           x = -73, y = 6,
                           alpha = 0.01, height = 622, by = 'height', size = 0.25) +
    # Rodent image
    geom_phylopic(image = "13ddd312-92ad-4873-9d65-4732b86cfbbd",
                           color = "steelblue", 
                           data = NULL, inherit.aes = FALSE,
                           x = -60, y = 13,
                           alpha = 0.01, height = 551, size = 0.25)
```

