---
title: 'Electronic Supplementary Material: Supplemental Methods and Results'
subtitle: "``Morphometric bases for intestinal paracellular absorption in bats and rodents''"
date: "`r Sys.setenv(TZ='America/Chicago'); format(Sys.Date(), '%d %b %Y')`"
author:
    - name: Antonio Brun
      nums: "1,2"
    - name: Guido Fernández Marinone
      nums: "1,2"
    - name: Edwin R. Price
      nums: "3"
    - name: Lucas A. Nell
      nums: "3"
    - name: Beatriz Marques
      nums: "4"
    - name: Alexandre Castellar
      nums: "4"
    - name: Ariovaldo P. Cruz-Neto
      nums: "4"
    - name: William H. Karasov
      nums: "3"
    - name: Enrique Caviedes-Vidal
      nums: "1,2"
affil:
    - name: Instituto Multidisciplinario de Investigaciones Biológicas de San Luis
      num: "1"
    - name: Universidad Nacional de San Luis
      num: "2"
    - name: University of Wisconsin--Madison
      num: "3"
    - name: Universidade Estadual Paulista ``Julio de Mesquita Filho'' Rio Claro
      num: "4"
fontsize: 12pt
csl: "ecology.csl"
bibliography: "references.bib"
geometry: margin=1in,letterpaper
documentclass: article
tables: true
graphics: true
colorlinks: true
supplemental: true
mathspec: true
output:
    bookdown::pdf_document2:
        fig_caption: yes
        number_sections: yes
        template: template.tex
        latex_engine: xelatex
        toc: yes
        toc_depth: 2
---

```{r setup, include=FALSE, cache = FALSE}
suppressPackageStartupMessages({
    library(knitr)
    library(knitcitations)
    library(bookdown)
})
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, dev = 'quartz_pdf')
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::knit_theme$set(knitr::knit_theme$get("acid"))

cleanbib()
options("citation_format" = "pandoc")
```


# Supplementary Methods

## Phylogeny

```{r phylogeny-main, child = 'phylo_tree.Rmd'}
```



## Jackknifing

```{r jackknifing-main, child = 'jackknifing.Rmd'}
```



# Supplementary Results

```{r results-main, child = 'results.Rmd'}
```


## `phylolm`

```{r results-phylolm-main, child = 'results-phylolm.Rmd'}
```


## `corphylo`

```{r results-corphylo-main, child = 'results-corphylo.Rmd'}
```


## Percent differences

```{r results-percent-main, child = 'results-percent.Rmd'}
```



# References

```{r biblio, message = FALSE}
write.bibtex(file="doc/references.bib")
```

