\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[12pt,]{article}
\usepackage{lmodern}
\usepackage{bbm}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{unicode-math}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Electronic Supplementary Material: Supplemental Methods and Results},
            colorlinks=true,
            linkcolor=Blue,
            citecolor=Blue,
            urlcolor=Blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in,letterpaper]{geometry}
\usepackage[labelfont=bf]{caption}
    \usepackage{longtable,booktabs}
            % Fix footnotes in tables (requires footnote package)
        \IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
    \usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure and tabke placement
\usepackage{float}
\makeatletter
\def\fps@figure{H}
\def\fps@table{H}
\makeatother

% Add S to the beginning of figure and table labels if it's supplemental section
    \renewcommand{\thefigure}{S\arabic{figure}}
    \renewcommand{\thetable}{S\arabic{table}}

\usepackage{placeins}
\usepackage[authoryear,sectionbib,sort]{natbib}
%% \bibliographystyle{plainnat}

\usepackage{authblk,etoolbox}
\renewcommand\Affilfont{\small}
\makeatletter
% patch \maketitle so that it doesn't center
\patchcmd{\@maketitle}{center}{flushleft}{}{}
\patchcmd{\@maketitle}{center}{flushleft}{}{}

% patch the patch by authblk so that the author block is flush left
\def\maketitle{{%
  \renewenvironment{tabular}[2][]
    {\begin{flushleft}}
    {\end{flushleft}}
  \AB@maketitle}}
\makeatother


\providecommand{\subtitle}[1]{\Large\emph{#1}}

\title{
    Electronic Supplementary Material: Supplemental Methods and Results
                \\
        \vspace*{1ex}
        \subtitle{``Morphological bases for intestinal paracellular absorption in bats and rodents''}
        }
    \author{}
% % \date{18 Apr 2019}
\date{}

\newcommand{\mean}[1]{\text{mean}\left( #1 \right)}
\newcommand{\var}[1]{\text{var}\left( #1 \right)}

% Removing extra space around \left( and \right)
\let\originalleft\left
\let\originalright\right
\renewcommand{\left}{\mathopen{}\mathclose\bgroup\originalleft}
\renewcommand{\right}{\aftergroup\egroup\originalright}


\usepackage{multirow}
\usepackage{array}
\usepackage{makecell}
\usepackage{rotating} % To display tables in landscape
\usepackage{siunitx} % Required for alignment



\begin{document}

            \maketitle
        


        {
                    \hypersetup{linkcolor=}
                \setcounter{tocdepth}{2}
        \tableofcontents
    }
    
\raggedright

\hypertarget{supplementary-methods}{%
\section{Supplementary Methods}\label{supplementary-methods}}

\hypertarget{phylogeny}{%
\subsection{Phylogeny}\label{phylogeny}}

The phylogenetic tree was downloaded from \href{timetree.org}{\texttt{timetree.org}}
\citep{Kumar_2017}.
Not every species in our phylogeny was used for every analysis.
Analyses related to morphometric, clearance, and absorption data had separate
datasets consisting of different species.
Figure \ref{fig:phylo-plot} shows the full phylogeny and which species were
present in each dataset.

\begin{figure}
\centering
\includegraphics{supp1_files/figure-latex/phylo-plot-1.pdf}
\caption{\label{fig:phylo-plot}Phylogeny of species used in these analyses. Boxes on the right indicate whether the species was used in morphometric (``morph.''), absorption (``absorp.''), or clearance (``clear.'') analyses. Gray boxes indicate a species was absent. The scale is in millions of years.}
\end{figure}

\hypertarget{aggregating-data}{%
\subsection{Aggregating data}\label{aggregating-data}}

For the datasets of morphometric and clearance measurements, we simply calculated
means (\(\bar{z}\)) and standard errors (\(s_{\bar{z}}\)) for a species and
intestinal position \(p\) (\(p \in \{ 1, 2, 3 \}\)) as such:

\begin{equation}
\label{eq:aggr-sp-pos}
\begin{split}
    \mathbf{Z} &= 
\begin{bmatrix}
    f\left( x_{1,1} \right) & f\left( x_{1,2} \right) & f\left( x_{1,3} \right) \\
    f\left( x_{2,1} \right) & f\left( x_{2,2} \right) & f\left( x_{2,3} \right) \\
    \vdots & \vdots & \vdots \\
    f\left( x_{n,1} \right) & f\left( x_{n,2} \right) & f\left( x_{n,3} \right)
\end{bmatrix} \\
    \bar{z}_p &= \frac{1}{n} \sum_{i=1}^{n} \mathbf{Z}_{i,p} \\
    s_p &= \sqrt{ \frac{1}{n-1} \sum_{i=1}^{n}\left( \mathbf{Z}_{i,p} - \bar{z} \right)^2 } \\
    s_{\bar{z}(p)} &= \frac{ s_p }{ \sqrt{n} }
\end{split}
\end{equation}

where \(f\) is the transformation function (either log or identity),
\(x_{i,p}\) is the \(i\)th untransformed value of the focal measurement for segment \(p\),
and \(n\) is the number of samples for the focal species.

For measurements that were aggregated by species but had separate measurements by
intestinal position, we did the following:

\begin{equation}
\label{eq:aggr-sp}
\begin{split}
    \mathbf{Z} &= 
\begin{bmatrix}
    f\left( x_{1,1} \right) & f\left( x_{1,2} \right) & f\left( x_{1,3} \right) \\
    f\left( x_{2,1} \right) & f\left( x_{2,2} \right) & f\left( x_{2,3} \right) \\
    \vdots & \vdots & \vdots \\
    f\left( x_{n,1} \right) & f\left( x_{n,2} \right) & f\left( x_{n,3} \right)
\end{bmatrix} \\[1ex]
    \mathbf{z} &= \frac{1}{3} \begin{bmatrix}
    \sum_{p=1}^{3} \mathbf{Z}_{1,p} \\[1ex]
    \sum_{p=1}^{3} \mathbf{Z}_{2,p} \\
    \vdots \\
    \sum_{p=1}^{3} \mathbf{Z}_{n,p}
\end{bmatrix} \\
    \bar{z} &= \frac{1}{n} \sum_{i=1}^{n} \mathbf{z}_{i} \\
    s_p &= \sqrt{ \frac{1}{n-1} \sum_{i=1}^{n}\left( \mathbf{z}_{i} - \bar{z} \right)^2 } \\
    s_{\bar{z}(p)} &= \frac{ s_p }{ \sqrt{n} }
\end{split}
\end{equation}

We could not do this for the fractional absorption data because different
individuals were used for the various measurements necessary to get the final
parameter values for each species.
The final parameter, \(a\), equals the following:

\begin{equation}
\label{eq:absorption}
    a = \frac{ e / b }{ t }
\end{equation}

where \(b\) is probe content at the beginning,
\(e\) is probe content at the end,
and \(t\) is total intestinal surface area (i.e., \(\text{NSA} \times \text{SEF}\)).

For three species, the individuals used for measurements for this calculation are
split into three groups:
One set of individuals were used for \(b\), another for \(e\), and a third
for \(t\).
For the rest of the species, \(b\) and \(e\) were measured together, but
\(t\) was measured in a different set of individuals.

This is important because
\(\mean{ \frac{X}{Y} } \ne \frac{ \mean{X} }{ \mean{Y} }\) and
\(\var{ \frac{X}{Y} } \ne \frac{ \var{X} }{ \var{Y} }\).
But because \(\mean{ X Y } = \mean{X} \mean{Y}\) and
\(\var{XY} = \mean{X}^2 \var{Y} + \mean{Y}^2 \var{X} + \var{X} \var{Y}\),
we inversed estimates before taking means or variances to allow us to combine
these values.
(Since these are entirely different individuals, we're assuming they are
independent samples.)

To begin, equation \ref{eq:absorption} can be manipulated to the following:

\begin{equation}
\label{eq:absorption2}
    a = e \left( \frac{1}{b} \right) \left( \frac{1}{ t } \right)
\end{equation}

Now we did the following to get mean absorptions (\(\bar{a}\)) for a given species:

\begin{equation}
\label{eq:absorption3}
\begin{split}
    \bar{e} &= \frac{1}{n_e}\sum_{i=1}^{n_e}\left( e_i \right) \\
    \bar{B} &= \frac{1}{n_b}\sum_{j=1}^{n_b}\left( \frac{1}{ b_j } \right) \\
    \bar{T} &= \frac{1}{n_t}\sum_{k=1}^{n_t}\left( \frac{1}{ t_k } \right) \\
    \bar{a} &= \bar{e} \bar{B} \bar{T}
\end{split}
\end{equation}

where \(n_e\), \(n_b\), \(n_t\) are numbers of individuals from the focal species
that were sampled for \(e\), \(b\), and \(t\), respectively.
Uppercase letters are used to distinguish inversed parameters.
To estimate the standard error of \(a\) (\(s_{\bar{a}}\)), we did the following:

\begin{equation}
\label{eq:absorption4}
\begin{split}
    s_e^2 &= \frac{1}{n_e-1} \sum_{i=1}^{n_e}\left( e_{i} - \bar{e} \right)^2 \\
    s_B^2 &= \frac{1}{n_b-1} \sum_{i=1}^{n_b}\left( B_{i} - \bar{B} \right)^2 \\
    s_T^2 &= \frac{1}{n_t-1} \sum_{i=1}^{n_t}\left( T_{i} - \bar{T} \right)^2 \\
    s_{eB}^2 &= \left(\bar{e}\right)^2 s_B^2 + \left(\bar{B}\right)^2 s_e^2 + 
        s_e^2 s_B^2 \\
    s_{a}^2 &= \left(\bar{eB}\right)^2 s_T^2 + \left(\bar{T}\right)^2 s_{eB}^2 + 
        s_{eB}^2 s_T^2 \\
    s_{\bar{a}} &= \sqrt{\frac{ s_{a}^2 }{ \min\left( n_e, n_b, n_t \right) }}
\end{split}
\end{equation}

Lastly, we log-transformed \(\bar{a}\) and \(s_{\bar{a}}\) by using the following:

If\ldots

\begin{itemize}
\tightlist
\item
  \(X\) is lognormally distributed with mean \(M\) and variance \(V\)
\item
  \(Y = \log\left(X\right)\) with mean \(m\) and variance \(v\)
\end{itemize}

then\ldots

\begin{equation}
\label{eq:absorption-log}
\begin{split}
    v &= \log\left(\frac{V}{M^2} + 1 \right) \\
    m &= \log\left(M \right) - \frac{v}{2}
\end{split}
\end{equation}

\hypertarget{jackknifing}{%
\subsection{Jackknifing}\label{jackknifing}}

We used jackknifing to estimate how influential points were to \texttt{phylolm}
and \texttt{cor\_phylo} model estimates.
We first conducted jackknife replicates (1 per row in the dataset), where, for
replicate \(i\), we removed row \(i\) from the dataset and re-fit the original model
with the subsetted datset.
This resulted in an \(n\) by \(p\) matrix of the jackknifed coefficient estimates
(\(\mathbf{B}\)),
where \(n\) is the sample size and \(p\) the number of coefficients estimated.
For column \(j\) from 1 to \(p\), we did the following:

\begin{equation}
\label{eq:jackknife}
\begin{split}
    \mathbf{\hat{B}}_j &= \mathbf{B}_j - \mathbf{b}_{(0)j} \\
    \mathbf{\tilde{B}}_j &= \frac{ \mathbf{\hat{B}}_j - \mu_{\mathbf{\hat{B}}_j} }{ 
        \sigma_{\mathbf{\hat{B}}_j} }
\end{split}
\end{equation}

where \(\mathbf{B}_j\) refers to column \(j\) in \(\mathbf{B}\),
\(\mu_{\mathbf{\hat{B}}_j}\) and \(\sigma_{\mathbf{\hat{B}}_j}\) are the mean and
standard deviation of \(\mathbf{\hat{B}}_j\) respectively,
and \(\mathbf{b}_{(0)j}\) is the \(j\)th item from the initial vector of coefficient
estimates using the full dataset.
The output \(n\) by \(p\) matrix, \(\mathbf{\tilde{B}}\), presents influence-value
Z-scores (scaled to have a standard deviation of one and mean of zero).
We used the absolute value of these Z-scores for plotting.

\hypertarget{supplementary-results}{%
\section{Supplementary Results}\label{supplementary-results}}

This section displays all results from analyses using
\texttt{phylolm::phylolm}
\citep{Ho_2014} and
\texttt{phyr::cor\_phylo}
\citep{Zheng_2009}.
The \texttt{phyr} package is available from \url{http://github.com/daijiang/phyr}.

In the tables below, the ``estimate'' column is the maximum likelihood estimate
for the specified parameter,
while columns ``lower'' and ``upper'' are lower and upper bounds of the 95\% confidence
interval for the parameter estimate.
``P'' is the P-value for a parameter not being equal to zero.
Both P-values and CIs were obtained by parametric bootstrapping of the \texttt{phylolm}
or \texttt{cor\_phylo} model.
We do not present P-values for phylogenetic signals because they were bound
above zero by the models; thus confidence intervals are more informative.

\hypertarget{phylolm}{%
\subsection{\texorpdfstring{\texttt{phylolm}}{phylolm}}\label{phylolm}}

\hypertarget{model-estimates}{%
\subsubsection{Model estimates}\label{model-estimates}}

Tables \ref{tab:results-spp-summs}--\ref{tab:results-dist-summs} summarize the
coefficient estimates for all \texttt{phylolm} model fits.
The ``Y'' column indicates the dependent variable for the model, and
vertical whitespace separates rows of different models.
When the ``parameter'' column is of the form \(\beta_X\), it refers to the coefficient
for independent variable \(X\). \(X\) is one of the following:

\begin{itemize}
\tightlist
\item
  clade: binary variable whose value is 1 if the species is a bat (0 if a rodent)
\item
  mass: log-transformed body mass
\item
  omniv.: binary variable whose value is 1 if the species is omnivorous
\item
  carniv.: binary variable whose value is 1 if the species is carnivorous
\end{itemize}

When the ``parameter'' column is of the form phylo\(_Y\), it refers to the
phylogenetic signal parameter \(Y\);
\(Y\) takes different values depending on the phylogenetic error term:
\(\lambda\) for Pagel's lambda and \(\alpha\) for Ornstein-Uhlenbeck.

\begin{table}[t]

\caption{\label{tab:results-spp-summs}\texttt{phylolm} model summaries for analyses by species only. All Y variables were log-transformed for these analyses}
\centering
\begin{tabular}{llllll}
\toprule
Y & parameter & estimate & lower & upper & P\\
\midrule
absorption & $\beta_{\text{clade}}$ & $1.136$ & $0.8098$ & $1.464$ & $0.000$\\
 & $\beta_{\text{mass}}$ & $-0.9336$ & $-1.206$ & $-0.6821$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
intestinal length & $\beta_{\text{clade}}$ & $-0.5582$ & $-0.9437$ & $-0.172$ & $0.003$\\
 & $\beta_{\text{mass}}$ & $0.3077$ & $0.05138$ & $0.5832$ & $0.014$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
NSA & $\beta_{\text{clade}}$ & $-0.5312$ & $-0.8023$ & $-0.2753$ & $0.000$\\
 & $\beta_{\text{mass}}$ & $0.5562$ & $0.3702$ & $0.7462$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
SEF & $\beta_{\text{omniv.}}$ & $-0.2266$ & $-0.5027$ & $0.05169$ & $0.122$\\
 & $\beta_{\text{carniv.}}$ & $-0.0844$ & $-0.3491$ & $0.1605$ & $0.505$\\
 & phylo$_{\lambda}$ & $0.6087$ & $1 \mathrm{e}{-7}$ & $1$ & –\\
\addlinespace
total enterocytes & $\beta_{\text{clade}}$ & $0.2853$ & $-0.2823$ & $0.8363$ & $0.318$\\
 & $\beta_{\text{mass}}$ & $0.7166$ & $0.3237$ & $1.087$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villous surface area & $\beta_{\text{clade}}$ & $0.02009$ & $-0.3043$ & $0.3786$ & $0.922$\\
 & $\beta_{\text{mass}}$ & $0.6925$ & $0.4538$ & $0.9333$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
\bottomrule
\end{tabular}
\end{table}

\begin{table}[t]

\caption{\label{tab:results-prox-summs}\texttt{phylolm} model summaries for proximal intestinal segment analyses. $\dagger$ indicates Y variables that were log-transformed. $\star$ indicates the model that was fit using the Ornstein-Uhlenbeck model for the phylogenetic error term (see ``Uncertainty in regression of proximal crypt width on clade'' below for more information on this model fit).}
\centering
\begin{tabular}{llllll}
\toprule
Y & parameter & estimate & lower & upper & P\\
\midrule
crypt width & $\beta_{\text{clade}}$ & $-0.01049$ & $-0.03151$ & $0.01037$ & $0.302$\\
 & phylo$_{\lambda}$ & $0.993$ & $1 \mathrm{e}{-7}$ & $1$ & –\\
\addlinespace
crypt width$^{\star}$ & $\beta_{\text{clade}}$ & $-0.01077$ & $-0.02321$ & $0.00144$ & $0.089$\\
 & phylo$_{\alpha}$ & $0.01558$ & $0.008039$ & $0.5183$ & –\\
\addlinespace
enterocyte diameter & $\beta_{\text{clade}}$ & $-0.0006223$ & $-0.001767$ & $0.0005472$ & $0.314$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
enterocyte density$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.5986$ & $0.1513$ & $1.048$ & $0.004$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
intestinal diameter$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.06123$ & $-0.1338$ & $0.247$ & $0.527$\\
 & $\beta_{\text{mass}}$ & $0.292$ & $0.1625$ & $0.4201$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
SEF$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.4455$ & $0.2313$ & $0.6687$ & $0.000$\\
 & $\beta_{\text{mass}}$ & $0.1758$ & $0.02925$ & $0.3178$ & $0.018$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus height$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.1441$ & $-0.05631$ & $0.3543$ & $0.177$\\
 & $\beta_{\text{mass}}$ & $0.2536$ & $0.1161$ & $0.3895$ & $0.004$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus width & $\beta_{\text{clade}}$ & $-0.02021$ & $-0.03624$ & $-0.004963$ & $0.012$\\
 & $\beta_{\text{mass}}$ & $0.01487$ & $0.003912$ & $0.02539$ & $0.006$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
\bottomrule
\end{tabular}
\end{table}

\begin{table}[t]

\caption{\label{tab:results-mid-summs}\texttt{phylolm} model summaries for middle intestinal segment analyses. $\dagger$ indicates Y variables that were log-transformed.}
\centering
\begin{tabular}{llllll}
\toprule
Y & parameter & estimate & lower & upper & P\\
\midrule
crypt width & $\beta_{\text{clade}}$ & $-0.007331$ & $-0.01321$ & $-0.001737$ & $0.014$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
enterocyte diameter & $\beta_{\text{clade}}$ & $-0.001184$ & $-0.00234$ & $-1.516 \mathrm{e}{-5}$ & $0.047$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
enterocyte density$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.7739$ & $0.366$ & $1.171$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
intestinal diameter$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.007967$ & $-0.1984$ & $0.2049$ & $0.959$\\
 & $\beta_{\text{mass}}$ & $0.1927$ & $0.05162$ & $0.3261$ & $0.003$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
SEF$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.4122$ & $0.2175$ & $0.6078$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus height$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.3266$ & $0.1204$ & $0.5371$ & $0.001$\\
 & $\beta_{\text{mass}}$ & $0.1618$ & $0.02052$ & $0.3003$ & $0.023$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus width & $\beta_{\text{clade}}$ & $-0.01664$ & $-0.02887$ & $-0.005241$ & $0.004$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
\bottomrule
\end{tabular}
\end{table}

\begin{table}[t]

\caption{\label{tab:results-dist-summs}\texttt{phylolm} model summaries for distal intestinal segment analyses. $\dagger$ indicates Y variables that were log-transformed.}
\centering
\begin{tabular}{llllll}
\toprule
Y & parameter & estimate & lower & upper & P\\
\midrule
crypt width & $\beta_{\text{clade}}$ & $-0.008267$ & $-0.01265$ & $-0.003572$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
enterocyte diameter & $\beta_{\text{clade}}$ & $-0.0002774$ & $-0.001504$ & $0.0009059$ & $0.632$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
enterocyte density$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.7403$ & $0.3086$ & $1.167$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
intestinal diameter$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.01093$ & $-0.1691$ & $0.1937$ & $0.912$\\
 & $\beta_{\text{mass}}$ & $0.2638$ & $0.1337$ & $0.4006$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
SEF$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.6129$ & $0.3836$ & $0.8411$ & $0.000$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus height$^{\dagger}$ & $\beta_{\text{clade}}$ & $0.6213$ & $0.3738$ & $0.89$ & $0.000$\\
 & $\beta_{\text{mass}}$ & $0.1869$ & $0.01351$ & $0.356$ & $0.039$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & –\\
\addlinespace
villus width & $\beta_{\text{clade}}$ & $-0.009533$ & $-0.02308$ & $0.002934$ & $0.145$\\
 & phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $0.01453$ & –\\
\addlinespace
\bottomrule
\end{tabular}
\end{table}

\clearpage

\hypertarget{uncertainty-in-regression-of-proximal-crypt-width-on-clade}{%
\subsubsection{Uncertainty in regression of proximal crypt width on clade}\label{uncertainty-in-regression-of-proximal-crypt-width-on-clade}}

The model for \texttt{crypt\_width\ \textasciitilde{}\ clade} in the proximal segment, when using Pagel's
\(\lambda\), estimates a very strong phylogenetic signal
(Table \ref{tab:results-prox-summs}).
When providing a low starting value for \(\lambda\) (\(\lambda = 0.1\)),
the model converges to a very weak phylogenetic signal (\(\lambda = 10^{-7}\)),
but it still has a higher log likelihood at the strong phylogenetic signal
(\(\ell = 68.14\) at \(\lambda = 0.993\)) than at the weak signal
(\(\ell = 66.88\) at \(\lambda = 10^{-7}\)).

However, this model is sensitive to starting values, which suggests multiple peaks in
the likelihood profile.
Moreover, the models for the other segments show very weak phylogenetic signal
(\(\lambda = 10^{-7}\) for both),
and this model re-run with the Ornstein-Uhlenbeck model for phylogenetic error
(``OU''; \texttt{OUfixedRoot} in \texttt{phylolm}) has a higher log likelihood and
shows a much weaker phylogenetic signal (\(\ell = 68.54\) and \(\alpha = 0.0156\)) than
the version run with Pagel's lambda.
Thus the model likely had convergence issues using Pagel's lambda, so we
replaced the original model with one using the OU error model.

\hypertarget{influential-value-in-regression-of-intestinal-length-on-clade}{%
\subsubsection{Influential value in regression of intestinal length on clade}\label{influential-value-in-regression-of-intestinal-length-on-clade}}

\hypertarget{jackknifing-1}{%
\paragraph{Jackknifing}\label{jackknifing-1}}

We used jackknifing to determine how influential each point is to the coefficient
estimates in the \texttt{phylolm} model for \texttt{log\_intestinal\_length\ \textasciitilde{}\ clade}.
See equation \ref{eq:jackknife} for how I calculated influence absolute Z-scores.
Figure \ref{fig:results-influence-plots}
show that one species (\emph{Artibeus lituratus}) has a disproportionate effect on all
three coefficient estimates.

\begin{figure}
\centering
\includegraphics{supp1_files/figure-latex/results-influence-plots-1.pdf}
\caption{\label{fig:results-influence-plots}Influential points for the regression of intestinal length on clade and body mass. (A) Intestinal length against body mass where point sizes are proportional to their influence absolute Z-score, color indicates clade, and both axes are on the log scale. (B) Influence absolute Z-scores by species. For both plots, facet labels indicate which parameter influence-values pertain to.}
\end{figure}

\hypertarget{re-running-model-without-influential-point}{%
\paragraph{Re-running model without influential point}\label{re-running-model-without-influential-point}}

Table \ref{tab:results-re-run-summ-dfs} compares summaries of this model
with and without the influential value.
When that point is removed, we are much less sure about mass's influence on
intestinal length.
It does not, however, change our conclusions regarding the influence of clade
(P-value for \(\beta_{\text{clade}}\) with influential point:
0.003;
P without it: 0.000).

\begin{table}
\caption{\label{tab:results-re-run-summ-dfs}\texttt{phylolm} model estimates for regression of log(intestinal length) on clade and log(body mass), with (left) and  without (right) influential point present in dataset.}

\centering
\begin{tabular}{llll}
\toprule
parameter & estimate & lower & upper\\
\midrule
$\beta_0$ & $2.308$ & $1.238$ & $3.325$\\
$\beta_{\text{clade}}$ & $-0.5582$ & $-0.9437$ & $-0.172$\\
$\beta_{\text{mass}}$ & $0.3077$ & $0.05138$ & $0.5832$\\
phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$\\
\bottomrule
\end{tabular}
\centering
\begin{tabular}{llll}
\toprule
parameter & estimate & lower & upper\\
\midrule
$\beta_0$ & $3.069$ & $2.118$ & $3.981$\\
$\beta_{\text{clade}}$ & $-0.8388$ & $-1.183$ & $-0.5138$\\
$\beta_{\text{mass}}$ & $0.1111$ & $-0.1144$ & $0.3456$\\
phylo$_{\lambda}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$ & $1 \mathrm{e}{-7}$\\
\bottomrule
\end{tabular}
\end{table}

\FloatBarrier

\hypertarget{cor_phylo}{%
\subsection{\texorpdfstring{\texttt{cor\_phylo}}{cor\_phylo}}\label{cor_phylo}}

Table \ref{tab:results-clear-sef-kable}
refers to \texttt{cor\_phylo} estimates for the correlation between clearance and SEF.
The table includes the Pearson correlation coefficient (\(r\)) between the two traits
and phylogenetic signals from an Ornstein-Uhlenbeck process for each individual trait.

\begin{table}[t]

\caption{\label{tab:results-clear-sef-kable}\texttt{cor\_phylo} model summary for the correlation between clearance and SEF. $r$ indicates the correlation and $d_X$ indicates the phylogenetic signal from an Ornstein-Uhlenbeck process for variable $X$. Both variables were log-transformed for this analysis.}
\centering
\begin{tabular}{lllll}
\toprule
parameter & estimate & lower & upper & P\\
\midrule
$r$ & $0.5806$ & $-0.1477$ & $0.9669$ & $0.103$\\
$d_{\text{sef}}$ & $0.9999$ & $4.552 \mathrm{e}{-5}$ & $1$ & –\\
$d_{\text{clear}}$ & $0.5632$ & $4.551 \mathrm{e}{-5}$ & $1$ & –\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{influential-value-for-correlation-between-clearance-and-sef}{%
\subsubsection{Influential value for correlation between clearance and SEF}\label{influential-value-for-correlation-between-clearance-and-sef}}

\hypertarget{jackknifing-2}{%
\paragraph{Jackknifing}\label{jackknifing-2}}

We used jackknifing to determine how influential each point is to the correlation
estimate in the \texttt{cor\_phylo} model for \texttt{clearance\ \textasciitilde{}\ SEF}.
See equation \ref{eq:jackknife} for how I calculated influence absolute Z-scores.
Figure \ref{fig:results-influence-plot-cp} shows that one species
(\emph{Tadarida brasiliensis}) has a disproportionate effect on the correlation.

\begin{figure}
\centering
\includegraphics{supp1_files/figure-latex/results-influence-plot-cp-1.pdf}
\caption{\label{fig:results-influence-plot-cp}Influential points for the correlation (Pearson's \(r\)) between clearance and SEF. (A) Clearance against SEF where point sizes are proportional to their influence absolute Z-score, color indicates clade, and both axes are on the log scale. (B) Influence absolute Z-scores by species.}
\end{figure}

\hypertarget{re-running-model-without-influential-point-1}{%
\paragraph{Re-running model without influential point}\label{re-running-model-without-influential-point-1}}

Table \ref{tab:results-re-run-summ-dfs-cor-phylo} shows the \texttt{cor\_phylo} output
when this influential point is excluded.

\begin{table}[t]

\caption{\label{tab:results-re-run-summ-dfs-cor-phylo}\texttt{cor\_phylo} model summary for the correlation between clearance and SEF without the most influential point. $r$ indicates the correlation and $d_X$ indicates the phylogenetic signal from an Ornstein-Uhlenbeck process for variable $X$. Both variables were log-transformed for this analysis.}
\centering
\begin{tabular}{lllll}
\toprule
parameter & estimate & lower & upper & P\\
\midrule
$r$ & $0.9227$ & $0.6044$ & $1$ & 0.004\\
$d_{\text{sef}}$ & $0.7432$ & $4.556 \mathrm{e}{-5}$ & $1$ & –\\
$d_{\text{clear}}$ & $0.4781$ & $4.561 \mathrm{e}{-5}$ & $0.9999$ & –\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{percent-differences}{%
\subsection{Percent differences}\label{percent-differences}}

This section calculates the percent differences mentioned in the discussion and abstract.

We calculated rodent and bat estimates at \texttt{log(body\ mass)\ =\ 0} to remove the effect
of body mass.
Since all these variables were log-transformed, we then exponentiated
both rodent and bat estimates before computing the proportional, then percentage,
difference:

\begin{equation}
    100 \times \frac{ \exp\left( \beta_0 + \beta_{\text{clade}} \right) - 
        \exp\left( \beta_0 \right) }{ \exp\left( \beta_0 \right) }
\end{equation}

where \(\beta_0\) is the intercept and \(\beta_{\text{clade}}\) the coefficient for clade.

\begin{itemize}
\tightlist
\item
  \textbf{NSA:} \(-41.21\)\%
\item
  \textbf{SEF:} \(63.91\)\%
\item
  \textbf{Enterocyte density:} \(102.8\)\%
\end{itemize}

\subsection{Measurements of absorption of paracellular probes in bats and rodents}

\begin{sidewaystable}[!ht]

\fontsize{10}{12}\selectfont

\centering
\caption{Summary of measurements of absorption of 
paracellular probes in bats and rodents. Data are presented as species mean values.}
\label{tab:table-s8}

\begin{tabular}{p{0.125in}@{}lSlSSSSp{2.5in}}
\toprule

    \multicolumn{4}{l}{} & 
        \multicolumn{3}{c}{\makecell[bc]{\textbf{Whole-animal} \\ \textbf{fractional} \\ 
            \textbf{absorption} \\ 
            \textbf{(proportion)}${}^{\dagger}$}} &
    \multicolumn{1}{c}{\makecell[bc]{\textbf{Tissue-level} \\ \textbf{absorption} \\
        \textbf{(}$\mathbf{\mu}$\textbf{L min}${}^{\mathbf{-1}}$ \\
        \textbf{cm}${}^{\mathbf{2}}$\textbf{)}}} &
        {} \\

\cmidrule(r){5-7} \cmidrule(r){8-8}

    {} & 
        \multicolumn{1}{c}{\textbf{Species}} & 
        \multicolumn{1}{c}{\makecell[bc]{\textbf{Body} \\ \textbf{Mass} \\ \textbf{(g)}}} & 
        \multicolumn{1}{c}{\makecell[bc]{\textbf{Primary} \\ \textbf{Dietary} \\ \textbf{Nutrient}}} & 
        \multicolumn{1}{c}{\rotatebox[origin=lB]{90}{\textbf{Arabinose}}} &
        \multicolumn{1}{c}{\rotatebox[origin=lB]{90}{\textbf{Rhamnose}}} &
        \multicolumn{1}{c}{\rotatebox[origin=lB]{90}{\makecell[lc]{\textbf{Lactulose or} \\ 
            \textbf{Cellobiose}}}} &
        \multicolumn{1}{c}{\rotatebox[origin=lB]{90}{\textbf{Arabinose}}} &
        \multicolumn{1}{c}{\textbf{Reference(s)}} \\
        
\midrule
\addlinespace[2ex]

    \multicolumn{9}{l}{Rodents:} \\
\addlinespace[1ex]
    & \emph{Peromyscus leucopus}      & 22.4  & Protein       & 0.31  &       & 0.12  & 0.974 & \citep{price2014} \\
    & \emph{Mus musculus}             & 30    & Carb/Prot     & 0.21  & 0.19  &       & 1.564 & \citep{caviedes2007, fasulo2013a, brun2014} \\
    & \emph{Microtus pennsylvanicus}  & 35.4  & Carbohydrate  & 0.22  &       & 0.15  &       & \citep{price2016} \\
    & \emph{Akodon montensis}         & 37    & Carb/Prot     & 0.35  &       &       & 3.98  & \citep{brun2014} \\
    & \emph{Onychomys leucogaster}    & 38    & Protein       & 0.40  &       & 0.13  & 1.257 & \citep{price2014} \\
    & \emph{Acomys cahirinus}         & 58    & Carbohydrate  & 0.42  &       & 0.05  &       & \citep{karasov2012} \\
    & \emph{Acomys russatus}          & 58    & Carbohydrate  & 0.31  &       & 0.14  &       & \citep{karasov2012} \\
    & \emph{Galea galea}              & 247   & Carbohydrate  &       & 0.22  & 0.08  &       & \citep{caviedes2007} \\
    & \emph{Rattus norvegicus}        & 300   & Carb/Prot     & 0.34  & 0.13  & 0.09  & 1.38  & \citep{lavin2007, brun2014} \\

\addlinespace[2ex]
\midrule[0.25pt]
\addlinespace[2ex]

    \multicolumn{9}{l}{Bats:} \\
\addlinespace[1ex]
    & \emph{Myotis lucifugus}             & 7.8   & Protein           & 0.82  &       & 0.57  & 2.812 & \citep{price2014} \\
    & \emph{Glossophaga soricina}         & 10    & Carbohydrate      &       &       &       & 13.68 & \citep{price2015} \\
    & \emph{Tadarida brasiliensis}        & 13    & Protein           & 1.03  &       &       & 1.91  & \citep{fasulo2013b, price2013} \\
    & \emph{Carollia perspicillata}       & 16    & Carbohydrate      &       &       &       & 8.81  & \citep{brun2014} \\
    & \emph{Eptesicus fuscus}             & 17.9  & Protein           & 0.85  &       &       &       & \citep{price2016} \\
    & \emph{Leptonycteris yerbabuenae}    & 20    & Carbohydrate      &       & 0.71  & 0.23  &       & \citep{rodriguez2016} \\
    & \emph{Sturnira lilium}              & 22    & Carbohydrate      & 1.2   &       &       & 14.03 & \citep{brun2014} \\
    & \emph{Desmodus rotundus}            & 34    & Protein           &       &       &       & 2.92  & \citep{price2015} \\
    & \emph{Artibeus lituratus}           &       & Carbohydrate      &       & 0.9   & 0.1   & 15.9  & \citep{caviedes2007, brun2014} \\
    & \emph{Rousettus aegyptiacus}        & 125   & Carbohydrate      &       & 0.62  & 0.22  &       & \citep{tracy2007} \\

\addlinespace[2ex]
\bottomrule
\addlinespace[2ex]
\end{tabular}

\raggedright

Notes:

$\dagger$ Different sized probe molecules are used in order to characterize the
molecular-size discrimination characteristics of the paracellular pathway.
All these compounds are inert, nonactively transported compounds that bracket in
molecular size D-glucose (molecular radius $\sim 3.9$ \AA{} \citep{pappenheimer1951}):
L-arabinose ($\sim 3.1$ \AA; \citep{schultz1961}), 
L-rhamnose ($\sim 3.7$ \AA; \citep{hamilton1987}; and 
lactulose and cellobiose (both $\sim 5$ \AA; \citep{hamilton1987}).

\end{sidewaystable}

\clearpage

\hypertarget{references}{%
\section{References}\label{references}}

\bibliographystyle{amnatnat.bst}

                            \bibliography{references.bib}
            


\end{document}
